name: publish to nuget
on:
  repository_dispatch:
    types: [trigger-workflow-2]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: NuGet Publisher
        # You may pin to the exact commit or the version.
        # uses: Jacup/publish-nuget@0d7b0c6f119fadaf9c3e2bcfcbb3bf3a1c439864
        uses: Jacup/publish-nuget@v2.6.0
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: KalorAform.MultiwayTree
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: KalorAform.MultiwayTree
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{ secrets.NUGET_API_KEY_FOR_MULTIWAYTREE }}
